apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qce54ft8k-java-springboot
  janus-idp.io/tekton: qce54ft8k-java-springboot
  backstage.io/kubernetes-id: qce54ft8k-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qce54ft8k-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
